site_name: HPC Framework Docs
site_url: https://gorgomel.github.io/Heuristic_Benchmarking_Framework/
repo_url: https://github.com/Gorgomel/Heuristic_Benchmarking_Framework
theme:
  name: material

nav:
  - Home: index.md
  - Protocol: protocol/proto_v3.1.1.md
  - API:
    - Generator CLI: api/generator_cli.md
    - Heuristics (Greedy): api/heuristics_greedy.md
    - Framework CLI: api/hpc_framework_cli.md
    - SSH Orchestrator: api/orchestrator_ssh_executor.md
  - Reports:
    - Instance Generator: reports/01_instance_generator.md
    - Experimental Campaign: reports/02_experimental_campaign.md
  - Decisions:
    - 001 Language Choice: decisions/001_choice_heuristic_language.md
    - 003 Methodology: decisions/003_metodologia_gerador_e_analise.md
    - 004 Testing & CI: decisions/004_testing_and_ci.md


plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: table
            show_source: false
            show_signature: true
            separate_signature: true
            merge_init_into_class: true
  - minify:
      minify_html: true
