site_name: HPC Framework Docs
site_url: https://gorgomel.github.io/Heuristic_Benchmarking_Framework/
repo_url: https://github.com/Gorgomel/Heuristic_Benchmarking_Framework
theme:
  name: material

nav:
  - Home: index.md
  - API:
      - generator/cli: api/generator_cli.md
      - heuristics/greedy: api/heuristics_greedy.md
      - hpc_framework/cli: api/hpc_framework_cli.md
      - orchestrator/ssh_executor: api/orchestrator_ssh_executor.md
  - Testing:
      - Overview: testing/TESTING.md
      - CI: testing/CI.md
      - Traceability: testing/TRACEABILITY.md
      - Cases:
          - TC_001_modularity_gate: testing/testcases/TC_001_modularity_gate.md
          - TC_002_cv_ceiling: testing/testcases/TC_002_cv_ceiling.md
          - TC_003_schema_freeze: testing/testcases/TC_003_schema_freeze.md
          - TC_004_cli_examples: testing/testcases/TC_004_cli_examples.md
          - TC_005_perf_smoke: testing/testcases/TC_005_perf_smoke.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]       # <- em vez de setup_commands
          options:
            docstring_style: google
            docstring_section_style: table
            show_source: false
            show_signature: true
            separate_signature: true
            merge_init_into_class: true
  - minify:
      minify_html: true
