---
name: CI (minimal)

on:
  push:
    branches: [main, dev]
    paths-ignore: [ "site/**" ]
  pull_request:
    branches: [main, dev]
    paths-ignore: [ "site/**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System deps (METIS for gpmetis)
        run: |
          sudo apt-get update
          sudo apt-get install -y metis
          gpmetis -h | head -n1 || true

      - name: Install Python deps (pip only)
        run: |
          python -m pip install --upgrade pip
          # test runner
          pip install pytest
          # instala o projeto a partir do pyproject (poetry-core)
          pip install .

      - name: Run tests
        env:
          OMP_NUM_THREADS: "1"
          OPENBLAS_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
        run: pytest -q
