name: ci
on: [push, pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - uses: abatilo/actions-poetry@v3
        with: { poetry-version: "1.8.3" }
      - name: Install
        run: |
          poetry install -E metrics --no-interaction
      - name: Lint & Type
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run mypy src
      - name: Tests + Coverage
        run: |
          poetry run pytest --cov=src --cov-report=term-missing --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
