name: Nightly Smokes

on:
  schedule:
    - cron: "0 3 * * *" # 03:00 UTC diariamente
  workflow_dispatch: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - name: Install
        run: |
          poetry env use "3.11"
          poetry install -E metrics --no-interaction
      - name: Run smokes and aggregate
        env:
          HPC_SMOKE_OUTDIR: data/results_raw/solvers_smoke
        run: |
          mkdir -p "$HPC_SMOKE_OUTDIR"
          poetry run pytest -q -m smoke || true
          poetry run python scripts/aggregate_manifests.py --in-glob "$HPC_SMOKE_OUTDIR/*.v1.json" --out "$HPC_SMOKE_OUTDIR/manifest_index.csv" || true
      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts
          path: |
            data/results_raw/solvers_smoke/**
          if-no-files-found: ignore
